### ISSUE TITLE
卡拉 Web 版在没有输入密码就点击登录后，再次输入密码，登录按钮也不可用。

### ISSUE THREAD

**Issue by myfor** [AiursoftWeb/AiurUI#14]
![TIM图片20200616093551](https://user-images.githubusercontent.com/50647468/84722073-cdcd9d80-afb4-11ea-8a5b-71e0033f8033.png)

像上图一样，没有输入密码就点击登录按钮，光标会跳到密码框并禁用登录按钮，但是再次输入密码后登录按钮也不能点击。
谷歌浏览器和火狐浏览器都是一样的结果。

**Comment by Anduin2017** [comment]
Fixed.
